POST http://localhost:8080/orders
Content-Type: application/json

{
"orders": [
  {"weight":1.1, "regions":1, "delivery_hours": ["09:00-11:00", "09:00-11:00"], "cost": 100},
  {"weight":2.1, "regions":2, "delivery_hours": ["09:00-11:00", "09:00-11:00"], "cost": 200}
]
}

###
POST http://localhost:8080/orders
Content-Type: application/json

{
"orders": [
{"weight":1.1, "regions":1, "delivery_hours": ["09:00-11:00", "09:00-11:00"], "cost": 100},
]
}

###
//“09:00-11:00”, “12:00-23:00”, “00:00-23:59”.

###
GET http://localhost:8080/orders/1
#Accept: application/json
#
####
GET localhost:8080/orders/2
#
####
GET localhost:8080/orders/3
#
####
GET localhost:8080/orders/4
#
####
GET localhost:8080/orders/88
#
####
#GET localhost:8080/orders?offset=0&limit=10

###
GET localhost:8080/orders
#
####
#GET http://localhost:8080/orders?limit=f
#Accept: application/json
#
####
#GET http://localhost:8080/orders?offset=4
#Accept: application/json
#
####
#GET http://localhost:8080/orders?limit=4
#Accept: application/json
#
####
#GET http://localhost:8080/orders?limit=0
#Accept: application/json
#
####
#GET http://localhost:8080/orders
#Accept: application/json
#
####
#GET http://localhost:8080/orders?limit=0&offset=e
#Accept: application/json
#
####
#GET http://localhost:8080/orders?limit=0&offset=0
#Accept: application/json


###
GET http://localhost:8080/couriers/meta-info/1?startDate=2023-01-20&endDate=2023-01-21
Accept: application/json
#
####
#GET http://localhost:8080/couriers/meta-info/1?startDate=2023-01-20&endDate=2024-01-21
#Content-Type: application/json
#
#{}
#`HH:MM-HH:MM`.

###
POST http://localhost:8080/couriers
Content-Type: application/json

{
  "couriers": [
    {
      "courier_type": "FOOT",
      "regions": [1, 2],
      "working_hours": ["12:00-14:30"]
    }
  ]
}

###
POST http://localhost:8080/orders/complete
Content-Type: application/json

{
  "complete_info": [
    {
      "courier_id": 1,
      "order_id": 4,
      "complete_time": "2024-01-06T18:31:20.477Z"
    }
  ]
}

###